---

# Targeting specific OSes or distributions:
#
#   - `ansible_system`               → Linux, BSD, ...
#   - `ansible_os_family`            → Debian, RedHat, ...
#   - `ansible_distribution`         → Debian, Ubuntu, RedHat, ...
#   - `ansible_distribution_release` → precise, wheezy, ...
#   - `ansible_pkg_mgr`              → apt, yum, ...

- name: Install Supervisord
  become: yes
  when: ansible_os_family == 'Debian'
  apt:
    name: supervisor
    state: present
    update_cache: yes
  register: __supervisord_installed
  tags:
    - deps
    - supervisor
    - supervisord
